# NumPy Exercises

## Overview

This notebook covers NumPy arrays, focusing on array attributes, creation, indexing, and other operations.

## Learning Objectives

- Understand NumPy ndarray attributes
- Create arrays using various NumPy functions
- Access array elements through basic indexing and slicing
- Perform advanced indexing on NumPy arrays
- Execute operations on NumPy arrays

## Prerequisites

- Basic understanding of Python
- NumPy library installed

## Get Started

To begin working with this notebook, import the NumPy library, and create an example array to work with in subsequent exercises.

In [ ]:
# Import the numpy library for numerical operations
import numpy as np

# Create a numpy array containing the values 1 through 6
arr = np.array([1, 2, 3, 4, 5, 6])

# Display the numpy array
arr

Then, run through the exercises in each section.

## NumPy ndarray attributes

What is the shape of the array **arr**?

In [ ]:
# Your code goes here

What is the type of elements in the array **arr**?

In [ ]:
# Your code goes here

## Creating arrays

Create a 3 by 3 matrix of integers

In [ ]:
# Your code goes here

Create a 2 by 4 matrix containing only zeros

In [ ]:
# Your code goes here

Create a 2 by 4 matrix containing only ones

In [ ]:
# Your code goes here

Create a 3 by 3 identity matrix

In [ ]:
# Your code goes here

Create a 3 by 4 matrix of random numbers

In [ ]:
# Your code goes here

## Accessing array elements

### Basic indexing and slicing

In [ ]:
# Create a 1D array of integers from 0 to 11, then reshape it into a 3D array
# with dimensions 2×2×3 (2 layers, each with 2 rows and 3 columns)
arr = np.arange(12).reshape(2, 2, 3)

# Display the array
# Will output:
# array([[[ 0,  1,  2],    # Layer 0, Row 0
#         [ 3,  4,  5]],   # Layer 0, Row 1
#        [[ 6,  7,  8],    # Layer 1, Row 0
#         [ 9, 10, 11]]])  # Layer 1, Row 1
arr

What is the first slice of the array **arr**?

In [ ]:
# Your code goes here

In [ ]:
# Create a 1D array containing integers from 0 to 9 (10 elements total)
# np.arange(10) generates a sequence starting at 0, stopping before 10
arr = np.arange(10)

# Display the array
# Will output:
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

What are the first five elements of the array **arr**?

In [ ]:
# Your code goes here

What are the last five elements of the array **arr**?

In [ ]:
# Your code goes here

What are the 3rd through 6th elements of the array **arr**?

In [ ]:
# Your code goes here

In [ ]:
# Create a 1D array of integers from 0 to 26, then reshape it into a 3×3×3 3D array
# (3 layers, each with 3 rows and 3 columns, making a 3D cube of 27 elements)
arr = np.arange(27).reshape(3, 3, 3)

# Display the array
# Will output:
# array([[[ 0,  1,  2],    # Layer 0, Row 0
#         [ 3,  4,  5],    # Layer 0, Row 1
#         [ 6,  7,  8]],   # Layer 0, Row 2
#        [[ 9, 10, 11],    # Layer 1, Row 0
#         [12, 13, 14],    # Layer 1, Row 1
#         [15, 16, 17]],   # Layer 1, Row 2
#        [[18, 19, 20],    # Layer 2, Row 0
#         [21, 22, 23],    # Layer 2, Row 1
#         [24, 25, 26]]])  # Layer 2, Row 2
arr

How do you access the third column of the array **arr**?

In [ ]:
# Your code goes here

### Advanced indexing

In [ ]:
# Create a 1D array with values from 0 to 8
arr = np.arange(9)  

# Reshape the 1D array into a 3x3 matrix
arr = arr.reshape(3, 3)  

# Display the resulting 3x3 array
arr  

How do you get a new array consists of the element in the first row, second column, and second row, first column?

In [ ]:
# Your code goes here

In [ ]:
# Create a NumPy array containing the names of three cities
cities = np.array(["Newark", "Wilmington", "Dover"])

# Generate a 3x4 array of random numbers sampled from a standard normal distribution (mean=0, std=1)
# This array represents some data associated with the cities (e.g., measurements, statistics, etc.)
city_data = np.random.randn(3, 4)

# Display the generated city data
city_data

How do you access city_data for Wilmington?

In [ ]:
# Your code goes here

How do you access positive elements in city_data?

In [ ]:
# Your code goes here

How do you replace negative elements in city_data with 0?

In [ ]:
# Replace all elements in `city_data` that are less than 0 with 0
# `city_data < 0` creates a boolean array of the same shape as `city_data`, where each element is:
# - True if the corresponding element in `city_data` is less than 0
# - False otherwise
# The boolean array is used to index `city_data`, and all elements satisfying the condition are set to 0
city_data[city_data < 0] = 0

# Display the modified `city_data` array
city_data

## Operations on arrays

In [ ]:
# Create a 1D array with values ranging from 0 to 14 (15 elements)
arr = np.arange(15)

# Reshape the 1D array into a 2D array with 3 rows and 5 columns
arr = arr.reshape(3, 5)

# Display the reshaped array
arr

How do you double all the elements in the array **arr**?

In [ ]:
# Multiply every element in the array `arr` by 2
# This operation is performed element-wise, meaning each value in the array is multiplied by 2
arr * 2

In [ ]:
# Create a 3x3 NumPy array `A` with the following values:
# [[1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]]
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create another 3x3 NumPy array `B` with the following values:
# [[9, 8, 7],
#  [6, 5, 4],
#  [3, 2, 1]]
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

What are the dot product of matrix **A** and **B**?

In [ ]:
# Your code goes here

In [ ]:
# Create a 1D array with values ranging from 0 to 14 (15 elements)
A = np.arange(15)

# Reshape the 1D array into a 2D array with 3 rows and 5 columns
A = A.reshape(3, 5)

# Display the reshaped array
A

How do you get the transpose of the matrix **A**?

In [ ]:
# Compute the transpose of the array `A`
# The transpose of a matrix swaps its rows and columns
A_transpose = A.T

# Display the transposed array
A_transpose

How do you calculate the Singular Value Decomposition of matrix **A**? (Hint: *linalg.svd*)

In [ ]:
# Your code goes here

## Conclusion

In this exercise, you've learned how to:

- Examine NumPy array attributes like shape and data type
- Create arrays using functions such as `np.array()`, `np.zeros()`, `np.ones()`, `np.identity()`, and `np.random.randn()`
- Access array elements using basic indexing, slicing, and advanced indexing techniques
- Perform operations on arrays, including element-wise operations, matrix multiplication, and linear algebra operations like Singular Value Decomposition
- These skills form the foundation for more advanced data manipulation and analysis using NumPy.

## Clean up

Remember to shut down your Jupyter notebook when you're finished to free up resources.